spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/reservation-service
    username: sample
    password: sample
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    include: credential
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: reservation-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: info, health


token:
  secret: sample