spring:
  datasource:
    url: jdbc:mariadb://15.164.85.227:3306/reservation-service
    username: sample
    password: sample
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    include: credential
  jpa:
    hibernate:
      ddl-auto: create