spring:
  datasource:
    url: jdbc:mariadb://15.164.85.227:3306/reservation-service
    username: sample
    password: sample
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    include: credential
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: reservation-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,info,metrics,prometheus

token:
  secret: sample

42meet:
  server:
    host: http://42meet.kro.kr
    login: http://42meet.kro.kr/login
    redirect: http://42meet.kro.kr/booking
    test: http://localhost:3000