spring:
  datasource:
    url: jdbc:mariadb://15.164.85.227:3306/reservation-service
    username: 42meet
    password: 1q2w3e4r
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: reservation-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

token:
  secret: sample
